### ISSUE TITLE
Syntax error in gsmmodem.py

### ISSUE THREAD

**Issue by tmcw** [adammck/pygsm#2]
It looks like line 692 of gsmmodem.py has a syntax error:

Traceback (most recent call last):
  File "sms_rest.py", line 1, in <module>
    import cherrypy, pygsm, sqlite3, ConfigParser
  File "/Users/tmcw/Apps/sms_rest/pygsm/**init**.py", line 5, in <module>
    from gsmmodem import GsmModem
  File "/Users/tmcw/Apps/sms_rest/pygsm/gsmmodem.py", line 692
    except Exception as err:
                      ^
Replacing 'as', with a comma works.

**Comment by adammck** [comment]
Fixed by SHA: f44f4aa5884f34a58ba59aa4e0db631c969ddca6
