### ISSUE TITLE
erron in gsmmodem.py

### ISSUE THREAD

**Issue by ghost** [adammck/pygsm#7]
```
>>> import pygsm
>>> m = pygsm.GsmModem(port="/dev/ttyS0")
>>> m.send_sms("+919500889199", "testing from python")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.5/site-packages/pygsm/gsmmodem.py", line 794, in send_sms
    self._write(chr(27))
  File "/usr/lib/python2.5/site-packages/pygsm/gsmmodem.py", line 268, in _write
    self.device.write(str)
AttributeError: 'NoneType' object has no attribute 'write'
```

**Comment by pnv1193** [comment]
I'm having the same issue. Please help.

**Comment by adammck** [comment]
Try calling `m.boot` before calling `m.send.sms`. This could definitely be better documented.
